# 4. Build et Push de l'image Backend FastAPI
    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend-api
        file: ./backend-api/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/task-manager-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/task-manager-backend:${{ steps.vars.outputs.SHA_SHORT }}

    # 5. Build et Push de l'image Frontend Manager Web
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend-web
        file: ./frontend-web/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/task-manager-web:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/task-manager-web:${{ steps.vars.outputs.SHA_SHORT }}
